In [1]:
import pyspedas
from pytplot import tplot

In [7]:
mms_fgm = pyspedas.mms.fpi(trange=['2017-01-26/08:13:04', '2017-01-26/08:17:04'], probe='1', data_rate='brst')
mms_fgm = pyspedas.mms.fgm(trange=['2017-01-26/08:13:04', '2017-01-26/08:17:04'], probe='1', data_rate='brst')

30-Sep-20 11:29:32: Loading /home/janmes/Documents/PhD/PhD-Starter-Project/mms_data/mms1/fpi/brst/l2/des-moms/2017/01/26/mms1_fpi_brst_l2_des-moms_20170126081303_v3.3.0.cdf
30-Sep-20 11:29:32: Loading /home/janmes/Documents/PhD/PhD-Starter-Project/mms_data/mms1/fpi/brst/l2/dis-moms/2017/01/26/mms1_fpi_brst_l2_dis-moms_20170126081303_v3.3.0.cdf
Loaded variables:
mms1_des_errorflags_brst
mms1_des_compressionloss_brst
mms1_des_startdelphi_count_brst
mms1_des_startdelphi_angle_brst
mms1_des_sector_despinp_brst
mms1_des_pitchangdist_lowen_brst
mms1_des_pitchangdist_miden_brst
mms1_des_pitchangdist_highen_brst
mms1_des_energyspectr_px_brst
mms1_des_energyspectr_mx_brst
mms1_des_energyspectr_py_brst
mms1_des_energyspectr_my_brst
mms1_des_energyspectr_pz_brst
mms1_des_energyspectr_mz_brst
mms1_des_energyspectr_par_brst
mms1_des_energyspectr_anti_brst
mms1_des_energyspectr_perp_brst
mms1_des_energyspectr_omni_brst
mms1_des_numberdensity_brst
mms1_des_densityextrapolation_low_brst
mms1_des_densi

In [8]:
from pytplot import store_data
store_data('mms1_des_tempparaperp_brst', data=['mms1_des_temppara_brst', 'mms1_des_tempperp_brst'])
store_data('mms1_dis_tempparaperp_brst', data=['mms1_dis_temppara_brst', 'mms1_dis_tempperp_brst'])

tplot(['mms1_fgm_b_gse_brst_l2','mms1_des_bulkv_gse_brst', 'mms1_des_numberdensity_brst', 'mms1_des_tempparaperp_brst', 'mms1_dis_tempparaperp_brst', 'mms1_dis_energyspectr_omni_brst', 'mms1_des_energyspectr_omni_brst'])

30-Sep-20 11:29:44: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



In [9]:
tplot('mms1_fgm_b_gse_brst_l2')

30-Sep-20 11:36:41: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



In [18]:
pytplot.data_quants['mms1_fgm_b_gse_brst_l2']

<xarray.DataArray 'mms1_fgm_b_gse_brst_l2' (time: 31872, v_dim: 4)>
array([[ 0.6730632 ,  0.67499435,  7.565788  ,  7.6256    ],
       [ 0.6988267 ,  0.70879847,  7.5809016 ,  7.645968  ],
       [ 0.70086867,  0.747079  ,  7.6168427 ,  7.685417  ],
       ...,
       [-7.5073147 ,  3.1807914 , -0.7831017 ,  8.190876  ],
       [-7.5040283 ,  3.1544054 , -0.77861845,  8.177222  ],
       [-7.4950423 ,  3.1393707 , -0.7792656 ,  8.163245  ]],
      dtype=float32)
Coordinates:
  * time     (time) float64 1.485e+09 1.485e+09 ... 1.485e+09 1.485e+09
Dimensions without coordinates: v_dim
Attributes:
    plot_options:  {'xaxis_opt': {'axis_label': 'Time', 'crosshair': 'X', 'x_...

In [14]:
pytplot.data_quants['mms1_fgm_b_gse_brst_l2'].values

30-Sep-20 11:38:51: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



array([[ 0.6730632 ,  0.67499435,  7.565788  ,  7.6256    ],
       [ 0.6988267 ,  0.70879847,  7.5809016 ,  7.645968  ],
       [ 0.70086867,  0.747079  ,  7.6168427 ,  7.685417  ],
       ...,
       [-7.5073147 ,  3.1807914 , -0.7831017 ,  8.190876  ],
       [-7.5040283 ,  3.1544054 , -0.77861845,  8.177222  ],
       [-7.4950423 ,  3.1393707 , -0.7792656 ,  8.163245  ]],
      dtype=float32)

In [28]:
import numpy as np
pytplot.data_quants['mms1_fgm_b_gse_brst_l2'].values[:,3][:10]

array([7.6256   , 7.645968 , 7.685417 , 7.688025 , 7.705061 , 7.741749 ,
       7.759007 , 7.7591395, 7.763428 , 7.784916 ], dtype=float32)

In [31]:
np.shape(np.meshgrid(np.arange(0, 10), np.arange(10, 20), np.arange(20, 30)))

30-Sep-20 11:44:14: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



(3, 10, 10, 10)

In [37]:
pytplot.data_quants['mms1_fgm_r_gse_brst_l2']

<xarray.DataArray 'mms1_fgm_r_gse_brst_l2' (time: 12, v_dim: 4)>
array([[ 69671.4  , -23911.662,  11126.933,  74496.17 ],
       [ 69665.73 , -23879.963,  11134.154,  74481.77 ],
       [ 69659.96 , -23848.303,  11141.365,  74467.32 ],
       [ 69654.15 , -23816.594,  11148.567,  74452.81 ],
       [ 69648.28 , -23784.863,  11155.76 ,  74438.25 ],
       [ 69642.336, -23753.145,  11162.942,  74423.64 ],
       [ 69636.34 , -23721.367,  11170.115,  74408.98 ],
       [ 69630.3  , -23689.57 ,  11177.278,  74394.26 ],
       [ 69624.2  , -23657.729,  11184.432,  74379.49 ],
       [ 69618.01 , -23625.959,  11191.575,  74364.67 ],
       [ 69611.77 , -23594.102,  11198.71 ,  74349.8  ],
       [ 69605.48 , -23562.26 ,  11205.834,  74334.87 ]], dtype=float32)
Coordinates:
  * time     (time) float64 1.485e+09 1.485e+09 ... 1.485e+09 1.485e+09
Dimensions without coordinates: v_dim
Attributes:
    CDF:           {'VATT': {'CATDESC': 'Definitive Position in GSE coordinat...
    plot_options:  {'xaxis_opt': {'axis_label': 'Time', 'crosshair': 'X', 'x_...

In [43]:
from scipy.signal import resample

mag = pytplot.data_quants['mms1_fgm_b_gse_brst_l2'].values
pos = pytplot.data_quants['mms1_fgm_r_gse_brst_l2'].values

mag = {'x': mag[:,0], 'y': mag[:,1], 'z': mag[:,2]}
pos = {'x': pos[:,0], 'y': pos[:,1], 'z': pos[:,2]}

pos_interp = {}
for coord, num in zip(['x','y','z'], [0,1,2]):
    print(f'resampling pos_{coord} from {len(pos[coord])} -> {len(mag[coord])}')
    pos_interp[coord] = resample(pos[coord], len(mag[coord]))
    print(f'Done {coord}')

resampling pos_x from 12 -> 31872
Done x
resampling pos_y from 12 -> 31872
Done y
resampling pos_z from 12 -> 31872
Done z
(31872,)


In [48]:
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt

30-Sep-20 12:59:33: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



In [56]:
plt.plot(np.linspace(0, len(pos_interp['x']), num=len(pos['x'])), pos['x'])
plt.plot(pos_interp['x'])
plt.savefig('test.png')
plt.cla()

30-Sep-20 13:08:09: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



In [57]:
mag = pytplot.data_quants['mms1_fgm_b_gse_brst_l2'].values
pytplot.tplot_math.tinterp('mms1_fgm_b_gse_brst_l2','mms1_fgm_r_gse_brst_l2', replace=True)
pos = pytplot.data_quants['mms1_fgm_r_gse_brst_l2'].values
np.shape(pos)

30-Sep-20 13:16:21: /home/janmes/Documents/PhD/PhD-Starter-Project/env/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)



(31872, 4)

In [ ]:
km2m = 1e3
nT2T = 1e-9

fgm_all = pyspedas.mms.fgm(trange=['2017-01-26/08:13:04', '2017-01-26/08:17:04'], probe=['1','2','3','4'] , data_rate='brst')